rm(list=ls())
gc()
library(data.table)
library(tidyverse)
library(cluster)
library(ggfortify)
library(gridExtra)

set.seed(10)

#generate a vector of date times
generate_dates<-function(n,sd='2018-06-01',ed='2018-09-01'){
  sd<-as.POSIXct(as.Date(sd))
  ed<-as.POSIXct(as.Date(ed))
  dt<-as.numeric(difftime(ed,sd,units = 'secs'))
  ev<- sort(runif(n,0,dt))
  rt<-sd+ev
  return(rt)
}

get_celeb_names<-function(){
  #read in dataset with celeb names
  dir<-"C:/Users/me/Documents"
  setwd(dir)
  name<-fread('random_celeb_list.txt',header = F,stringsAsFactors = F)
  
  #create scrambled vector
  name[,name_hash:=apply(name[,2],MARGIN=1, function(x)base64enc::base64encode(charToRaw(x)))]
  return(name)
}

generate_random_uid<-function(dat){
  #get celeb names
  name<-get_celeb_names()

  x_coords<-unique(round(runif(length(name$name_hash),0,length(name$name_hash))))
  #create vector of 2000 users
  repeaters<-as.data.table(sample(name$name_hash[-x_coords],length(unique(dat[-x_coords])),replace = T))%>%
    setnames('V1','portal_id')
  non_repeaters<-as.data.table(sample(name$name_hash[x_coords],length(unique(dat[x_coords])),replace = F))%>%
    setnames('V1','portal_id')
  sam<-as.data.table(cbind(unique(dat),rbind(repeaters,non_repeaters)))[
    ,V1:=as.numeric(V1)]%>%
    setnames('V1','session')%>%
    merge(setNames(as.data.table(dat),nm='session'),by='session')
  
  return(sam[,2])
  }
  
session_counter<-function(x){
  j=1
  y=0
  for(i in 1:length(x)){
    if(x[i]<=20){
      y[i]=j
    }else if(x[i]>20){
      j=j+1
      y[i]=j
    }
  }
  return(y)
  }
#start data.table
#add lags by creating difftime in date time vector
#adding a session number
#add a portal_id

generate_random_dt<-function(no_dates){
df<-data.table(timestamp=generate_dates(no_dates))[
  ,time_lag:=rbind(setNames(as.data.frame(0),nm='lag'),setNames(as.data.frame(diff(timestamp,1)),nm='lag'))][
    ,session:=session_counter(time_lag)][
      ,portal_id:=generate_random_uid(session)]
}

df<-generate_random_dt(no_dates=2000000)
user_db<-get_celeb_names()

#######Begin Cluster Analysis#########

assign_clusters<-function(i,holder){
  cat('\n  Running Kmeans on Month: ',i)
  #t<-clusGap(holder[,2:4],FUNcluster = kmeans,K.max = 10,B=100) #Find ideal Cluster centers
  #plot(t)
  clusters<-kmeans(holder[,3:5],centers = 4)    #Identifies user clusters in Data
  labels<-clusters$cluster                      #creates vector of clusters
  holder[,cluster:=clusters$cluster]
  cat('\nCluster appended for month',i)
  return(holder)
}

pivot_and_cluster<-function(month_no){
  cat(paste0('\nPivoting Month: ',month_no))
  pivot<-df[month(timestamp)==month_no,][   #Cuts by Month
    ,yearmo:=paste0(month(timestamp),year(timestamp))][ #create date
      ,maxt:=max(timestamp),by=session][      #Creates Max TS 
        ,mint:=min(timestamp),by=session][    #Creates Min TS
          ,session_time:=maxt-mint][          #Creates session time  
            ,.(session_time=mean(session_time),count_actions=.N,count_sessions=length(unique(session))),by=.(portal_id,yearmo)][  #Aggregates Sessiontime, Sessions, and Actions by user
              ,session_time:=as.numeric(session_time)]  #Formats
  cat('\nDone')
  cat('\nAssigning Clusters')
  holder<-assign_clusters(month_no,pivot)
  return(holder)}

make_clusplots<-function(i,holder){
  cat('\n    Running PCA on Month: ',i)
  pca<-princomp(holder[,3:5])                   #Reduces dimensionality among variables  
  pc_scores<-as.data.table(pca$scores[,1:2])                   #Pulls PCA 1 and 2
  cat('\n      Creating Cluster Plot for Month: ',i)
  #clusplot(pc_scores,labels,main=paste0('Cluster Plot for ',i,'-2018'))
  g<-autoplot(kmeans(holder[,3:5],4), data=holder[,3:5], frame=T, frame.type='norm')
  return(g)
  print(g)
}

create_clusters_across_months<-function(min_m=range(month(df$timestamp))[1],max_m=range(month(df$timestamp))[2]){
  cat(paste0('Min. Month: ',min_m,'\nMax. Month: ', max_m))
  clus_df<-data.table()
  pdf(paste0("Cluster_mapping",Sys.Date(),'.pdf')) #gloms the clusplots that are generated by the append clusters function, which inherits the clusplot from make_clusplots
  for(i in min_m:max_m){
    holder<-pivot_and_cluster(i)
    clus_df<-rbind(clus_df,holder)
    make_clusplots(i,holder)
    }
  dev.off()
  return(clus_df)
}

clus_df<-create_clusters_across_months()


pivot<-create_pivot(7)
clusters<-kmeans(pivot[,2:4],centers = 4)
labels<-clusters$cluster
pca<-princomp(pivot[,2:4])
pc_scores<-pca$scores[,1:2]
clusplot(pc_scores,labels) 

pivot[,cluster:=clusters$cluster]


pivot_june<-df[,maxt:=max(timestamp),by=session][
  ,mint:=min(timestamp),by=session][
    ,session_time:=maxt-mint][
      month(timestamp)==7,.(session_time=mean(session_time),count_actions=.N,count_sessions=length(unique(session))),by=portal_id][
        ,session_time:=as.numeric(session_time)]

#return(pivot)}

#pivot<-create_pivot(6)


clusters<-kmeans(pivot_june[,2:4],centers = 4)
labels<-clusters$cluster

pca<-princomp(pivot_june[,2:4])
pc_scores<-pca$scores[,1:2]
clusplot(pc_scores,labels) 

pivot_june[,cluster:=clusters$cluster]

summary(pivot_june$count_sessions[pivot_june$cluster==4])
summary(pivot_july$count_sessions[pivot_july$cluster==4])
